'use strict';
// Real, complete candidate pages are served at their canonical public paths. No destination HTML stubs.
const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.QA_OUTPUT||'suite-artifacts');fs.mkdirSync(out,{recursive:true});
const bases=JSON.parse(fs.readFileSync(path.join(root,'qa/ro-suite-nav-1.3.0/suite-heads.json')));
const entries=[
 ['Portal','ro_tools_portal',null,'portal'],['Leveling','ro-leveling-map','leveling-map','leveling'],['Reform','ro-reform-preparation','reform-workshop','reform'],['Dim Glacier','dim_glacier_planner','dim-glacier','dim'],['Ocean Week','sessrumnir-ocean-week-guide','ocean-week-guide','ocean'],['Best Status','ro-best-status','best-status','best']
].map(([label,repo,tool,key])=>({label,repo,tool,key,prefix:'/'+repo+'/',url:'https://econds.github.io/'+repo+'/',directory:key==='ocean'?root:path.join(process.env.SUITE_ROOT,key)}));
for(const e of entries){e.sha=execFileSync('git',['rev-parse','HEAD'],{cwd:e.directory,encoding:'utf8'}).trim();if(e.key!=='ocean')assert.equal(e.sha,bases[e.key].sha);e.publish=path.join(e.directory,e.key==='ocean'?'docs':'.');}
const report={status:'running',startedAt:new Date().toISOString(),sources:entries.map(({label,repo,sha,prefix})=>({label,repo,sha,prefix})),matrix:{},checks:[],failures:[],liveHealth:[],limitations:['Cross-repository transitions use Chromium desktop 1440×1000. Mobile, keyboard and theme matrices are tested in the per-repository suites; no physical devices or WebKit/Firefox.','Candidate pages are full unchanged application files served locally at canonical public paths via browser network routing. Destinations are not HTML stubs. Production child sites remain 1.2.0 until merge.','Optional catalog failure is tested on an explicitly attributed isolated fixture; production integrations keep catalog-url absent.','Public URL health is measured separately and does not imply deployed version matches candidates.']};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const check=async(name,fn)=>{try{await fn();report.checks.push({name,status:'PASS'});}catch(e){report.failures.push({name,error:e.stack});report.checks.push({name,status:'FAIL'});}};
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.woff2':'font/woff2','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://local');const entry=entries.find(e=>u.pathname.startsWith(e.prefix));if(!entry){res.writeHead(404);return res.end('Unknown site');}let f=path.resolve(entry.publish,decodeURIComponent(u.pathname.slice(entry.prefix.length))||'index.html');if(!f.startsWith(path.resolve(entry.publish)+path.sep)){res.writeHead(403);return res.end();}try{const b=fs.readFileSync(f);res.writeHead(200,{'Content-Type':mime[path.extname(f)]||'application/octet-stream'});res.end(b);}catch{res.writeHead(404);res.end('Missing '+u.pathname);}});
let browser;
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const local='http://127.0.0.1:'+server.address().port;browser=await chromium.launch();report.browser=browser.version();report.playwright=require('playwright/package.json').version;
 const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
 await context.route('https://econds.github.io/**',async route=>{const u=new URL(route.request().url());if(!entries.some(e=>u.pathname.startsWith(e.prefix)))return route.continue();const response=await context.request.get(local+u.pathname+u.search);await route.fulfill({response});});
 const page=await context.newPage();const startupErrors=[];page.on('pageerror',e=>startupErrors.push(e.message));page.on('requestfailed',r=>{if(r.url().startsWith('https://econds.github.io/')&&r.resourceType()==='script')startupErrors.push(r.url()+': '+r.failure()?.errorText);});
 const ready=async(e)=>{await page.locator('body').waitFor();if(e.tool){await page.locator('ro-suite-nav .bar button').waitFor();assert.equal(await page.locator('ro-suite-nav').getAttribute('tool-id'),e.tool);}assert((await page.locator('body').innerText()).length>100);};
 for(const from of entries.filter(e=>['leveling','reform','dim','ocean'].includes(e.key))){report.matrix[from.label]={};for(const to of entries){await check(from.label+' -> '+to.label,async()=>{await page.goto(from.url,{waitUntil:'networkidle'});await ready(from);const host=page.locator('ro-suite-nav');if(to.tool)await host.locator('.bar button').click();const link=to.tool?host.locator('#tools a[href="'+to.url+'"]'):host.locator('.bar > a');assert.equal(await link.count(),1);await link.click();await page.waitForURL(to.url);await page.waitForLoadState('networkidle');await ready(to);if(to.tool){await page.locator('ro-suite-nav .bar button').click();assert.equal(await page.locator('ro-suite-nav #tools [aria-current="page"]').getAttribute('href'),to.url);}else{assert(await page.locator('a[href="https://econds.github.io/ro-best-status/"]').count()>0);}assert.deepEqual(startupErrors,[],'No page errors or failed app scripts during actual transitions');report.matrix[from.label][to.label]='PASS';});if(!report.matrix[from.label][to.label])report.matrix[from.label][to.label]='FAIL';}}
 for(const from of entries.filter(e=>['leveling','reform','dim','ocean'].includes(e.key))){await check(from.label+' optional catalog failure fixture + production snapshot/state',async()=>{
 await page.goto(from.url+'?suite=preserve#suite-check',{waitUntil:'networkidle'});await ready(from);const host=page.locator('ro-suite-nav');assert.equal(await host.getAttribute('catalog-url'),null);
 const before=await page.evaluate(()=>({url:location.href,storage:{...localStorage}}));
 const catalog='https://econds.github.io/ro_tools_portal/catalog/v1/tools.json';let attempted=0;await page.route(catalog,route=>{attempted++;return route.abort('failed');});
 // Construct a fresh test-only host, so first-open fetch uses this explicit optional attribute.
 await page.evaluate(({tool,catalog})=>{const old=document.querySelector('ro-suite-nav');const next=document.createElement('ro-suite-nav');for(const a of old.attributes)next.setAttribute(a.name,a.value);next.setAttribute('catalog-url',catalog);next.innerHTML=old.innerHTML;old.replaceWith(next);},{tool:from.tool,catalog});
 const b=page.locator('ro-suite-nav .bar button');await b.click();await page.waitForTimeout(1700);assert.equal(attempted,1);
 const actual=await page.locator('ro-suite-nav #tools a').evaluateAll(es=>es.map(e=>({url:e.href,current:e.getAttribute('aria-current'),text:e.textContent.trim()})));
 assert.deepEqual(actual.map(x=>x.url),entries.filter(e=>e.tool).map(e=>e.url));assert.equal(actual.find(x=>x.current==='page').url,from.url);assert.equal(actual.find(x=>x.url.endsWith('/ro-best-status/')).text,'Best Status');
 assert.equal(await page.locator('ro-suite-nav #tools a').filter({hasText:'Grade & Refine'}).count(),0);assert(await page.locator('ro-suite-nav #tools').innerText().then(x=>x.includes('Grade & Refine')));
 await page.keyboard.press('Escape');assert.equal(await b.getAttribute('aria-expanded'),'false');assert(await b.evaluate(e=>e.getRootNode().activeElement===e));assert.deepEqual(await page.evaluate(()=>({url:location.href,storage:{...localStorage}})),before);
 await page.unroute(catalog);
 });}
 // Every candidate uses exactly the same immutable 1.3.0 bytes; old1.2 remains locally available.
 for(const e of entries.filter(e=>['leveling','reform','dim','ocean','best'].includes(e.key))){await check(e.label+' exact 1.3.0 release',async()=>{const d=path.join(e.publish,'assets/ro-suite/1.3.0');const lock=JSON.parse(fs.readFileSync(path.join(d,'nav.lock.json')));assert.equal(lock.bundleVersion,'1.3.0');for(const [file,h]of Object.entries({'nav.js':'e0a75bce3f8ba21d73aff8aa28af1c624d977f1e8e3de483c6dd40785b3b84d2','catalog.snapshot.json':'a198338ddcb7857094ef950fb1315c532840cf53ac8e7a69b331d8cb4a87dd5d','nav.lock.json':'7ac31d27c493071ad164326022854a637c5015ae7989ff8c2a4c129b021c59c3'})){assert.equal(sha(fs.readFileSync(path.join(d,file))),h);if(file!=='nav.lock.json')assert.equal(lock.files[file].sha256,h);}if(e.key!=='best')assert(fs.existsSync(path.join(e.publish,'assets/ro-suite/1.2.0/nav.js')));});}
 // Separate actual network health; no browser routing is applied to API requests.
 for(const e of entries){await check(e.label+' live URL health',async()=>{const r=await context.request.get(e.url);report.liveHealth.push({url:e.url,status:r.status(),finalUrl:r.url()});assert.equal(r.status(),200);assert.equal(r.url(),e.url);});}
 await context.close();
}catch(e){report.failures.push({name:'runner',error:e.stack});}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));report.status=report.failures.length?'FAIL':'PASS';report.finishedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'cross-repo-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exitCode=report.failures.length?1:0;}})();
